APP_NAME=POLARIS_SMART_ACCESS_SERVICE
APP_DB_USER=polaris_dev
APP_DB_PASSWORD=${DB_PASSWORD}
APP_DB_NAME=polaris_master
APP_DB={"type":"mysql","host":"10.193.1.227","port":4000,"maxOpenConnection":10,"maxIdleConnection":5,"connectionMaxLifetimeSecond":60,"retryMax":5,"retryIntervalSecond":1,"logMode":1,"tlsOrSslMode":"false"}
APP_GENERAL={"refreshIntervalMs":60000,"cacheType":"local","publishLogs":false,"autoCleanPeriodDays":7,"autoCleanSleepMs":1000}
APP_LOCAL_CACHE={"shards":1,"lifeWindowMs":600000,"cleanWindowMs":60000,"maxEntrySizeMb":1,"hardMaxCacheSizeMb":64,"verbose":true,"refreshIntervalMs":60000}
APP_LOG={"level":"debug","format":"custom-text","outputFile":"","timestampFormat":"2006-01-02 15:04:05.000"}
APP_REDIS_SERVER={"type":"STANDALONE","hosts":["10.193.1.63:6379"],"password":"","maxRedirects":3,"poolSize":10,"poolTimeout":1000}
APP_REST_SERVER={"name":"POLARIS_SMART_ACCESS_SERVICE","port":8081,"contextPath":"/api/v1","mode":"debug","registry":false}
APP_GRPC_SERVER={"name":"POLARIS_SMART_ACCESS_SERVICE","address":":28081","maxConcurrentStreamsMs":1000,"maxConnectionIdleMs":900000,"timeMs":120000,"timeoutMs":120000}
APP_RMQ_CLIENT={"address":"localhost:28080","check":false}
KEYCLOAK_HOST=10.193.1.63:8080
KEYCLOAK_REALM=titipaja
KEYCLOAK_PROTOCOL=http
KEYCLOAK_ADMIN_USER=admin
KEYCLOAK_ADMIN_PASS=${KEYCLOAK_ADMIN_PASSWORD}
KEYCLOAK_ADMIN_CLIENT_ID=polaris
LOGIN_MAX_FAILED_ATTEMPTS=5
LOGIN_RATE_LIMIT_WINDOW_MIN=15
LOGIN_LOCK_DURATION_MIN=30
SES_TIMEOUT_MIN=15
MASTER_DATA_SERVICE_GRPC_ADDRESS=10.193.1.228:32537
KEYCLOAK_REDIRECT_URI=http://10.193.1.228:30080/auth/login
